name: Robot Framework Tests with Allure and GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
          pip install allure-robotframework
          pip install robotframework-browser

      - name: Instalar Allure CLI
        run: |
          sudo apt update
          sudo apt install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Executar testes Robot Framework com listener Allure
        run: |
          mkdir -p results/allure-results  # Cria diretório se não existir
          robot \
          -v NAVEGADOR:headlesschrome \
          -v CHROME_OPTIONS:'{"args": ["--headless", "--no-sandbox", "--disable-dev-shm-usage", "--user-data-dir=/tmp/chrome-user-data"]}' \
          --listener allure_robotframework:results/allure-results \
          -d results \
          tests/

      - name: Publicar resultados do Allure como artefato
        if: always()  
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: results/allure-results/

      - name: Gerar relatório HTML do Allure
        if: always()  
        run: |
          mkdir -p results/allure-report  # Cria diretório se não existir
          allure generate results/allure-results --clean -o results/allure-report
          ls -la results/allure-report  # Lista conteúdo para debug

      - name: Publicar relatório Allure no GitHub Pages
        if: always() 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./results/allure-report
          keep_files: true 

      - name: Exibir link do relatório Allure
        run: |
          echo "Relatório disponível em: https://HugoSMonteiro.github.io/desafio_coco_bambu/"
          echo "Se não aparecer, aguarde alguns minutos para o GitHub Pages atualizar"